import { Device, Alert, LoRaMetric, SensorReading } from './types';

export const mockDevices: Device[] = [
  {
    id: 'device-001',
    name: 'North Field Sensor 1',
    type: 'soil-sensor',
    location: 'Field A - North',
    status: 'online',
    lastUpdate: new Date(Date.now() - 5 * 60000),
    batteryLevel: 85,
    soilMoisture: 62,
    temperature: 24.5,
    humidity: 68,
    rssi: -85,
    snr: 8.5,
  },
  {
    id: 'device-002',
    name: 'South Field Sensor 2',
    type: 'soil-sensor',
    location: 'Field B - South',
    status: 'online',
    lastUpdate: new Date(Date.now() - 3 * 60000),
    batteryLevel: 72,
    soilMoisture: 45,
    temperature: 26.2,
    humidity: 55,
    rssi: -92,
    snr: 6.2,
  },
  {
    id: 'device-003',
    name: 'Weather Station Central',
    type: 'weather-station',
    location: 'Farm Center',
    status: 'online',
    lastUpdate: new Date(Date.now() - 2 * 60000),
    batteryLevel: 95,
    temperature: 25.1,
    humidity: 62,
    rssi: -75,
    snr: 10.8,
  },
  {
    id: 'device-004',
    name: 'East Field Sensor 3',
    type: 'soil-sensor',
    location: 'Field C - East',
    status: 'warning',
    lastUpdate: new Date(Date.now() - 15 * 60000),
    batteryLevel: 28,
    soilMoisture: 78,
    temperature: 27.8,
    humidity: 71,
    rssi: -105,
    snr: 3.1,
  },
  {
    id: 'device-005',
    name: 'West Field Sensor 4',
    type: 'soil-sensor',
    location: 'Field D - West',
    status: 'offline',
    lastUpdate: new Date(Date.now() - 2 * 3600000),
    batteryLevel: 5,
    soilMoisture: undefined,
    temperature: undefined,
    humidity: undefined,
  },
  {
    id: 'gateway-001',
    name: 'LoRa Gateway Main',
    type: 'gateway',
    location: 'Farm Headquarters',
    status: 'online',
    lastUpdate: new Date(Date.now() - 1 * 60000),
    batteryLevel: 100,
    rssi: -65,
    snr: 12.5,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    deviceId: 'device-004',
    deviceName: 'East Field Sensor 3',
    severity: 'critical',
    message: 'Battery level critically low (28%)',
    timestamp: new Date(Date.now() - 10 * 60000),
    isResolved: false,
  },
  {
    id: 'alert-002',
    deviceId: 'device-002',
    deviceName: 'South Field Sensor 2',
    severity: 'warning',
    message: 'Soil moisture below threshold (45%)',
    timestamp: new Date(Date.now() - 20 * 60000),
    isResolved: false,
  },
  {
    id: 'alert-003',
    deviceId: 'device-005',
    deviceName: 'West Field Sensor 4',
    severity: 'critical',
    message: 'Device offline for 2 hours',
    timestamp: new Date(Date.now() - 90 * 60000),
    isResolved: false,
  },
  {
    id: 'alert-004',
    deviceId: 'device-001',
    deviceName: 'North Field Sensor 1',
    severity: 'info',
    message: 'Temperature trending upward',
    timestamp: new Date(Date.now() - 3 * 60000),
    isResolved: false,
  },
  {
    id: 'alert-005',
    deviceId: 'device-003',
    deviceName: 'Weather Station Central',
    severity: 'info',
    message: 'Humidity level stabilized',
    timestamp: new Date(Date.now() - 120 * 60000),
    isResolved: true,
  },
];

export const mockLoRaMetrics: LoRaMetric[] = [
  {
    deviceId: 'device-001',
    deviceName: 'North Field Sensor 1',
    rssi: -85,
    snr: 8.5,
    pdr: 98.5,
    latency: 45,
    lastUpdate: new Date(Date.now() - 5 * 60000),
  },
  {
    deviceId: 'device-002',
    deviceName: 'South Field Sensor 2',
    rssi: -92,
    snr: 6.2,
    pdr: 95.2,
    latency: 62,
    lastUpdate: new Date(Date.now() - 3 * 60000),
  },
  {
    deviceId: 'device-003',
    deviceName: 'Weather Station Central',
    rssi: -75,
    snr: 10.8,
    pdr: 99.8,
    latency: 28,
    lastUpdate: new Date(Date.now() - 2 * 60000),
  },
  {
    deviceId: 'device-004',
    deviceName: 'East Field Sensor 3',
    rssi: -105,
    snr: 3.1,
    pdr: 72.3,
    latency: 185,
    lastUpdate: new Date(Date.now() - 15 * 60000),
  },
];

export const mockSensorData: Record<string, SensorReading[]> = {
  'device-001': [
    { id: '1', timestamp: new Date(Date.now() - 0), value: 62, unit: '%' },
    { id: '2', timestamp: new Date(Date.now() - 3600000), value: 58, unit: '%' },
    { id: '3', timestamp: new Date(Date.now() - 7200000), value: 55, unit: '%' },
    { id: '4', timestamp: new Date(Date.now() - 10800000), value: 59, unit: '%' },
    { id: '5', timestamp: new Date(Date.now() - 14400000), value: 64, unit: '%' },
  ],
  'device-002': [
    { id: '1', timestamp: new Date(Date.now() - 0), value: 45, unit: '%' },
    { id: '2', timestamp: new Date(Date.now() - 3600000), value: 48, unit: '%' },
    { id: '3', timestamp: new Date(Date.now() - 7200000), value: 51, unit: '%' },
    { id: '4', timestamp: new Date(Date.now() - 10800000), value: 49, unit: '%' },
    { id: '5', timestamp: new Date(Date.now() - 14400000), value: 46, unit: '%' },
  ],
};

export const mockKPIs = {
  totalDevices: mockDevices.length,
  onlineDevices: mockDevices.filter((d) => d.status === 'online').length,
  offlineDevices: mockDevices.filter((d) => d.status === 'offline').length,
  averageSoilMoisture: 58.25,
  averageTemperature: 25.9,
  activeAlerts: mockAlerts.filter((a) => !a.isResolved).length,
  networkHealth: 94.7,
};
